name: Build and Deploy Snapshot
on: [push]
permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # JDK 17 has a few failures so cannot yet enable for this module
        java_version: ['8', '11']
        os: ['ubuntu-20.04']
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - run: inotifywait -mr /home/runner/work/jackson-databind/jackson-databind/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
    - run: touch starting_build_uses34_34
    - run: rm starting_build_uses34_34
    - uses: actions/checkout@v3
    - run: touch starting_build_SetupJDK_35
    - run: rm starting_build_SetupJDK_35
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java_version }}
        cache: 'maven'
        server-id: sonatype-nexus-snapshots
        server-username: CI_DEPLOY_USERNAME
        server-password: CI_DEPLOY_PASSWORD
        # See https://github.com/actions/setup-java/blob/v2/docs/advanced-usage.md#Publishing-using-Apache-Maven
        # gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
        # gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
    - run: touch starting_build_Build_47
    - run: rm starting_build_Build_47
    - name: Build
      run: ./mvnw -B -ff -ntp clean verify
    - run: touch starting_build_ExtractprojectMavenversion_49
    - run: rm starting_build_ExtractprojectMavenversion_49
    - name: Extract project Maven version
      id: projectVersion
      run: echo ::set-output name=version::$(./mvnw org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -DforceStdout -Dexpression=project.version -q)
    - run: touch starting_build_Deploysnapshot_52
    - run: rm starting_build_Deploysnapshot_52
    - name: Deploy snapshot
      env:
        CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
        CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
        # MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      run: ./mvnw -B -q -ff -DskipTests -ntp source:jar deploy
    - run: touch starting_build_Generatecodecoverage_59
    - run: rm starting_build_Generatecodecoverage_59
    - name: Generate code coverage
      run: ./mvnw -B -q -ff -ntp test
    - run: touch starting_build_Publishcodecoverage_62
    - run: rm starting_build_Publishcodecoverage_62
    - name: Publish code coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./target/site/jacoco/jacoco.xml
        flags: unittests
    - run: touch starting_finished_finished_8979874
      if: always()
    - run: rm starting_finished_finished_8979874
      if: always()
    - name: Execute py script # run file
      if: always()
      run: |
        python .github/workflows/script.py
    - run: cp /home/runner/inotify-logs.csv /home/runner/work/jackson-databind/jackson-databind/optimizing-ci-builds-ci-analysis/
      if: always()
    - name: Pushes analysis to another repository
      if: always()
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'optimizing-ci-builds-ci-analysis'
        destination-github-username: 'optimizing-ci-builds'
        destination-repository-name: 'ci-analyzes'
        target-branch: 'jackson-databind.1670424990'
        target-directory: 'jackson-databind/1670424990/.github/workflows/main/build'

